spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/push_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: KRApxf1xDB7Ff2awefRQupp6wAAMfHTvRY3U0zkvNho=
    password: eIMY+mFbPkujWgFNf6uOlF16JX2etFhgtc+1q3itb84=
    port: 465
    properties:
      mail:
        display:
          sendmail: zte-rail
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtps
    test-connection: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: push-center-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      thread:
        min: 2
        max: 5
      topic: push-center-topic
    producer:
      batch-size: 65536
      buffer-memory: 524288
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zte.msg.pushcenter.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0