spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.30.104:3306/push_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: zxwz
    password: Zxwz123!@#
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: push-center-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      thread:
        min: 2
        max: 3
      topic: push-center-topic
    producer:
      batch-size: 65536
      buffer-memory: 524288
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zte.msg.pushcenter.pccore.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: true
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
sign:
  verify: true

async:
  push:
   pool-size:
     core: 100
     max: 100
logging:
  file:
    path: ./log